//==============================================================================
// Module: gmii_phy_if
// Description: Pure GMII PHY interface wrapper
//
// Features:
//   - Transparent GMII signal passthrough
//   - No protocol logic
//   - Replaceable for different PHY types
//   - Signal-level connection only
//   - Optional IO register instantiation hooks
//
// Purpose:
//   This module serves as a clean interface point between the MAC and PHY.
//   For GMII PHYs, it is essentially a passthrough. The module exists to:
//   1. Provide a consistent interface pattern
//   2. Allow easy PHY substitution
//   3. Isolate any board-level signal conditioning
//
// GMII Signals (IEEE 802.3):
//   TX: GTX_CLK (125 MHz from MAC), TXD[7:0], TX_EN, TX_ER
//   RX: RX_CLK (125 MHz from PHY), RXD[7:0], RX_DV, RX_ER
//   Status: COL, CRS (for half-duplex)
//   Management: MDC, MDIO (optional, not included in Phase 0)
//
// Verification Hooks:
//   - Assertion: Signal integrity (no X/Z in active frame)
//   - Coverage: All signal combinations during transmission
//
// Author: AI-IP Generator
// License: MIT
//==============================================================================

module gmii_phy_if (
    //==========================================================================
    // Clock Interface
    //==========================================================================
    // TX clock (125 MHz, generated by MAC, output to PHY)
    input  wire        gtx_clk,         // TX clock from MAC
    output wire        phy_gtx_clk,     // TX clock to PHY

    // RX clock (125 MHz, generated by PHY, input to MAC)
    input  wire        phy_rx_clk,      // RX clock from PHY
    output wire        rx_clk,          // RX clock to MAC

    //==========================================================================
    // MAC-side Interface (directly from mac_top)
    //==========================================================================
    // TX signals (GTX clock domain)
    input  wire [7:0]  mac_txd,         // TX data from MAC
    input  wire        mac_tx_en,       // TX enable from MAC
    input  wire        mac_tx_er,       // TX error from MAC

    // RX signals (RX clock domain)
    output wire [7:0]  mac_rxd,         // RX data to MAC
    output wire        mac_rx_dv,       // RX data valid to MAC
    output wire        mac_rx_er,       // RX error to MAC

    // Status signals (directly passed through)
    output wire        mac_col,         // Collision to MAC
    output wire        mac_crs,         // Carrier sense to MAC

    //==========================================================================
    // PHY-side Interface (directly to PHY pins)
    //==========================================================================
    // TX signals (GTX clock domain)
    output wire [7:0]  phy_txd,         // TX data to PHY
    output wire        phy_tx_en,       // TX enable to PHY
    output wire        phy_tx_er,       // TX error to PHY

    // RX signals (RX clock domain)
    input  wire [7:0]  phy_rxd,         // RX data from PHY
    input  wire        phy_rx_dv,       // RX data valid from PHY
    input  wire        phy_rx_er,       // RX error from PHY

    // Status signals from PHY
    input  wire        phy_col,         // Collision from PHY
    input  wire        phy_crs          // Carrier sense from PHY
);

    //==========================================================================
    // Clock Passthrough
    // Note: In ASIC, these may need clock buffers
    // In FPGA, these will use BUFG/BUFR primitives (added in top-level wrapper)
    //==========================================================================
    assign phy_gtx_clk = gtx_clk;
    assign rx_clk      = phy_rx_clk;

    //==========================================================================
    // TX Signal Passthrough (MAC -> PHY)
    // Direct connection, no protocol modification
    //==========================================================================
    assign phy_txd   = mac_txd;
    assign phy_tx_en = mac_tx_en;
    assign phy_tx_er = mac_tx_er;

    //==========================================================================
    // RX Signal Passthrough (PHY -> MAC)
    // Direct connection, no protocol modification
    //==========================================================================
    assign mac_rxd   = phy_rxd;
    assign mac_rx_dv = phy_rx_dv;
    assign mac_rx_er = phy_rx_er;

    //==========================================================================
    // Status Signal Passthrough
    //==========================================================================
    assign mac_col = phy_col;
    assign mac_crs = phy_crs;

endmodule
